# coding: utf-8

"""
    RegexSolver API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GenerateStringsPathOrder(str, Enum):
    """
    Order in which the paths of the language are scheduled — the *shapes* the term allows, as opposed to the characters filling them (`characterOrder`). `sweep` expands one path in full, shortest first, before moving to the next one: the cheapest way to page through a whole language with `offset`. `interleave` covers every path the term holds before any path is asked for a second string, so a `limit` smaller than the number of shapes is spent entirely on distinct shapes; slower than `sweep`, but better suited to deriving test cases. `shuffled` is `interleave` with same-length paths visited in an order drawn by `seed`. Shorter paths still come first, so the seed only draws among paths of equal length. All three are deterministic and page with `offset`; for `shuffled`, offsets are only consistent between calls sharing the same `seed`.
    """

    """
    allowed enum values
    """
    SWEEP = 'sweep'
    INTERLEAVE = 'interleave'
    SHUFFLED = 'shuffled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenerateStringsPathOrder from a JSON string"""
        return cls(json.loads(json_str))


