# coding: utf-8

"""
    RegexSolver API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from regexsolver._generated.models.generate_strings_character_order import GenerateStringsCharacterOrder
from regexsolver._generated.models.generate_strings_path_order import GenerateStringsPathOrder
from regexsolver._generated.models.request_options import RequestOptions
from regexsolver._generated.models.term import Term
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GenerateStringsRequest(BaseModel):
    """
    Request to generate up to `limit` distinct strings matched by `term`, skipping the first `offset` strings and confined to lengths between `minLength` and `maxLength`. For consistent pagination, `term` should be deterministic.
    """ # noqa: E501
    term: Term = Field(description="Source term to generate strings from.")
    limit: Annotated[int, Field(le=100, strict=True, ge=1)] = Field(description="Maximum number of unique strings to return.")
    offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Number of matched strings to skip before starting to collect the results. Used for pagination.")
    min_length: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Shortest string to generate. Strings shorter than this are left out of the enumeration entirely, `offset` never counting them.", alias="minLength")
    max_length: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=100, description="Longest string to generate. Strings longer than this are left out of the enumeration entirely, `offset` never counting them. A value below `minLength` leaves nothing to generate.", alias="maxLength")
    path_order: Optional[GenerateStringsPathOrder] = Field(default=None, description="Order in which the paths of the language are scheduled. Defaults to `sweep`.", alias="pathOrder")
    character_order: Optional[GenerateStringsCharacterOrder] = Field(default=None, description="Order in which the strings within each path are produced. Defaults to `ascending`.", alias="characterOrder")
    seed: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Seed behind the `shuffled` modes of `pathOrder` and `characterOrder`; ignored when neither is used. The default seed is fixed rather than random, so two calls sharing a seed generate the same strings and `offset` pages through them consistently. Change it to draw a different sequence from the same term.")
    charset: Optional[StrictStr] = Field(default=None, description="Character class the generated strings are restricted to, such as `[a-z]` or `\\P{C}`. Paths needing a character outside of it are dropped entirely. If omitted, every character the term allows is used.")
    options: Optional[RequestOptions] = None
    __properties: ClassVar[List[str]] = ["term", "limit", "offset", "minLength", "maxLength", "pathOrder", "characterOrder", "seed", "charset", "options"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateStringsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of term
        if self.term:
            _dict['term'] = self.term.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        # set to None if charset (nullable) is None
        # and model_fields_set contains the field
        if self.charset is None and "charset" in self.model_fields_set:
            _dict['charset'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateStringsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "term": Term.from_dict(obj["term"]) if obj.get("term") is not None else None,
            "limit": obj.get("limit"),
            "offset": obj.get("offset") if obj.get("offset") is not None else 0,
            "minLength": obj.get("minLength") if obj.get("minLength") is not None else 0,
            "maxLength": obj.get("maxLength") if obj.get("maxLength") is not None else 100,
            "pathOrder": obj.get("pathOrder"),
            "characterOrder": obj.get("characterOrder"),
            "seed": obj.get("seed") if obj.get("seed") is not None else 0,
            "charset": obj.get("charset"),
            "options": RequestOptions.from_dict(obj["options"]) if obj.get("options") is not None else None
        })
        return _obj


