from typing import Optional, Union, cast

from regexsolver.generated.models import Term as GeneratedTerm
from regexsolver.generated.models.term_fair import TermFair
from regexsolver.generated.models.term_regex import TermRegex
from regexsolver.models.cardinality import Cardinality
from regexsolver.models.length import Length
from regexsolver.models.term_properties_mixin import TermPropertiesMixin


class Term:
    """Represents a mathematical term (Regex or FAIR) on which operations can be performed.

    This is a pure data model that holds the underlying pattern and caches
    computed properties (like length and cardinality) to minimize network I/O.
    """

    def __init__(self, generated_term: GeneratedTerm):
        """Initializes a new Term instance wrapping the generated API model.

        Args:
            generated_term (GeneratedTerm): The raw Pydantic model generated by OpenAPI.
        """
        self._inner_term = generated_term

        self._cardinality: Optional[Cardinality] = None
        self._length: Optional[Length] = None
        self._empty: Optional[bool] = None
        self._empty_string: Optional[bool] = None
        self._total: Optional[bool] = None
        self._pattern: Optional[str] = None
        self._dot: Optional[str] = None

    @property
    def _actual_model(self) -> Union[TermRegex, TermFair]:
        """Extracts the underlying concrete model from the generated OpenAPI oneOf wrapper."""
        actual = getattr(self._inner_term, "actual_instance", self._inner_term)
        return cast(Union[TermRegex, TermFair], actual)

    def _set_properties_mixin(self, properties_mixin: TermPropertiesMixin):
        """Updates internal cached properties based on trait inferences."""
        empty = properties_mixin.is_empty()
        if empty is not None:
            self._empty = empty

        empty_string = properties_mixin.is_empty_string()
        if empty_string is not None:
            self._empty_string = empty_string

        total = properties_mixin.is_total()
        if total is not None:
            self._total = total

    @property
    def type(self) -> str:
        """str: The format type of the underlying term (e.g., 'regex' or 'fair')."""
        return self._actual_model.type

    @property
    def value(self) -> str:
        """str: The raw string value of the term (the pattern or FAIR payload)."""
        return self._actual_model.value

    @property
    def _api_model(self) -> GeneratedTerm:
        """GeneratedTerm: Returns the raw generated model to be used in API requests."""
        return self._inner_term

    @classmethod
    def fair(cls, fair: str) -> "Term":
        """Creates a new Term from a Fast Automaton Internal Representation (FAIR) string.

        Args:
            fair: The FAIR encoded payload.

        Returns:
            Term: A new Term instance representing the FAIR payload.
        """
        gen_term = GeneratedTerm(TermFair(type="regex", value=fair))
        return cls(gen_term)

    @classmethod
    def regex(cls, pattern: str) -> "Term":
        """Creates a new Term from a regular expression string.

        Args:
            pattern: A valid regular expression string.

        Returns:
            Term: A new Term instance representing the regex.
        """
        gen_term = GeneratedTerm(TermRegex(type="regex", value=pattern))
        return cls(gen_term)

    def get_fair(self) -> Optional[str]:
        """Retrieves the FAIR payload if the term was explicitly constructed as one.

        Returns:
            Optional[str]: The FAIR payload string, or None if the term is a standard regex.
        """
        if self.type == "fair":
            return self.value
        return None

    def serialize(self) -> str:
        """Serializes the Term into a portable string format.

        Returns:
            str: The serialized string in the format 'type=value' (e.g., 'regex=[a-z]').
        """
        actual_model = self._actual_model
        return f"{actual_model.type}={actual_model.value}"

    @staticmethod
    def deserialize(string: str) -> Optional["Term"]:
        """Reconstructs a Term instance from a serialized string.

        Args:
            string: A string previously generated by `Term.serialize()`.

        Returns:
            Optional[Term]: The parsed Term instance, or None if parsing fails.
        """
        if not string or "=" not in string:
            return None
        prefix, value = string.split("=", 1)
        if prefix == "regex":
            return Term.regex(value)
        elif prefix == "fair":
            return Term.fair(value)
        return None

    def __str__(self) -> str:
        """Returns the serialized representation of the Term."""
        return self.serialize()

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Term):
            return self.type == other.type and self.value == other.value
        return False

    def __hash__(self) -> int:
        """Generates a hash based on the serialized string representation."""
        return hash(self.serialize())
